export type Block =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "list"; items: string[] }
  | { type: "callout"; icon: string; title: string; text: string }
  | { type: "quote"; text: string; author?: string }
  | { type: "table"; headers: string[]; rows: string[][] };

export interface Artigo {
  slug: string;
  titulo: string;
  desc: string;
  tempo: string;
  tags: { label: string; cls: string }[];
  autor: string;
  data: string;
  conteudo: Block[];
}

export const artigos: Artigo[] = [
  {
    slug: "como-llms-funcionam",
    titulo: "Como os LLMs funcionam: explicação sem código",
    desc: "Uma explicação visual e acessível de como modelos de linguagem processam texto e geram respostas.",
    tempo: "8 min",
    tags: [{ label: "Técnico", cls: "tagTecnico" }],
    autor: "IA Fala Brasil",
    data: "Mar 2026",
    conteudo: [
      { type: "p", text: "Você já se perguntou o que acontece nos bastidores quando você digita uma mensagem no ChatGPT ou no Claude e recebe uma resposta inteligente em segundos? Esses sistemas são chamados de LLMs — Large Language Models, ou Modelos de Linguagem de Grande Escala em português." },
      { type: "h2", text: "O que é um LLM?" },
      { type: "p", text: "Um LLM é um tipo de inteligência artificial treinado para entender e gerar texto. Ele aprendeu a fazer isso lendo uma quantidade absurda de texto — livros, sites, artigos, fóruns — antes de ser lançado ao público. Essa fase se chama pré-treinamento." },
      { type: "p", text: "Pense assim: se você lesse bilhões de frases em português, começaria a entender padrões — quais palavras costumam aparecer juntas, como construir uma resposta coerente, o que faz sentido depois de 'A capital do Brasil é...'. É exatamente isso que o modelo faz, mas em escala industrial." },
      { type: "h2", text: "Tokens: a língua secreta da IA" },
      { type: "p", text: "O modelo não lê palavras inteiras — ele divide o texto em pedaços menores chamados tokens. A palavra 'inteligência', por exemplo, pode virar dois tokens: 'intelig' + 'ência'. Em inglês, a maioria das palavras comuns é um único token." },
      { type: "p", text: "Por que isso importa? Porque o modelo tem um limite de quantos tokens consegue processar de uma vez (a chamada 'janela de contexto'). É como a memória de curto prazo: o que ficou para trás pode ser esquecido." },
      { type: "h2", text: "Como ele 'pensa' na resposta?" },
      { type: "p", text: "O LLM não raciocina como um humano — ele prevê qual token vem depois do anterior. Cada palavra gerada é escolhida com base em probabilidade: dada toda a conversa até agora, qual é o próximo token mais provável?" },
      { type: "callout", icon: "🎲", title: "Exemplo prático", text: "Se você digitar 'A banana é uma fruta de cor...', o modelo atribui alta probabilidade à palavra 'amarela'. Não porque 'sabe' que bananas são amarelas — mas porque esse padrão apareceu inúmeras vezes nos dados de treinamento." },
      { type: "h2", text: "Por que a IA 'mente'?" },
      { type: "p", text: "Como o modelo prevê tokens por probabilidade, às vezes ele gera respostas que parecem verdadeiras mas são inventadas. Isso se chama alucinação. O modelo não tem vergonha de inventar um nome de autor, uma lei ou uma data — ele simplesmente segue o padrão mais provável." },
      { type: "list", items: [
        "Verifique sempre informações importantes em fontes confiáveis",
        "Desconfie de nomes, datas e números específicos sem confirmação",
        "Use a IA para rascunhos e ideias, não como enciclopédia",
        "Pergunte ao modelo sua própria confiança na resposta",
      ]},
      { type: "h2", text: "RLHF: tornando a IA mais útil e segura" },
      { type: "p", text: "Após o pré-treinamento, os modelos passam por uma fase de ajuste fino com humanos avaliando respostas. Essa técnica se chama RLHF (Reinforcement Learning from Human Feedback). É ela que faz o modelo preferir respostas úteis e evitar conteúdo perigoso." },
      { type: "h2", text: "O que isso significa para o Brasil?" },
      { type: "p", text: "A maior parte dos LLMs foi treinada com dados predominantemente em inglês. Isso significa que o modelo conhece menos sobre o Brasil, nossa cultura, nossas leis e nosso contexto social. Ao usar IA para assuntos brasileiros — legislação, história, política — o risco de alucinação aumenta." },
      { type: "callout", icon: "🇧🇷", title: "Dica brasileira", text: "Ao perguntar sobre leis brasileiras, programas do governo ou história do Brasil, sempre confirme as informações no site oficial. O modelo pode citar leis que não existem ou confundir datas de legislações." },
    ],
  },

  {
    slug: "vies-racial-algoritmos-credito",
    titulo: "Viés racial em algoritmos de crédito no Brasil",
    desc: "Análise de casos reais em que modelos de IA reproduziram desigualdades históricas no acesso ao crédito.",
    tempo: "11 min",
    tags: [{ label: "Ética & IA", cls: "tagEtica" }],
    autor: "IA Fala Brasil",
    data: "Mar 2026",
    conteudo: [
      { type: "p", text: "Em um país onde 54% da população é preta ou parda (IBGE, 2022), e onde as desigualdades raciais são históricas e documentadas, algoritmos de crédito que reproduzem essas desigualdades não são apenas um problema técnico — são um problema de justiça social." },
      { type: "h2", text: "O que é viés algorítmico?" },
      { type: "p", text: "Viés algorítmico ocorre quando um modelo de IA toma decisões sistematicamente desfavoráveis para determinados grupos — por raça, gênero, região, renda — mesmo sem ter sido programado explicitamente para isso. O problema está nos dados usados para treinar o modelo." },
      { type: "callout", icon: "⚠️", title: "O ciclo vicioso dos dados históricos", text: "Se historicamente pessoas negras receberam menos crédito (por discriminação humana), os dados históricos registram isso como 'padrão'. O algoritmo aprende que pessoas negras são 'mau pagador' — não por comportamento real, mas por herança discriminatória dos dados." },
      { type: "h2", text: "Casos documentados no Brasil" },
      { type: "p", text: "Pesquisadores da USP e da FGV têm documentado casos em que sistemas de score de crédito apresentam disparidade racial significativa. Numa análise de 2024, solicitantes com nomes tipicamente afro-brasileiros receberam scores menores em média — mesmo com histórico financeiro idêntico a solicitantes com nomes de outras origens." },
      { type: "p", text: "O problema vai além do nome: CEP e endereço são variáveis comuns em modelos de crédito. Como a segregação residencial no Brasil é racialmente estratificada, usar CEP pode introduzir viés racial indiretamente — sem nunca mencionar raça." },
      { type: "h2", text: "As variáveis proxy" },
      { type: "p", text: "Variáveis proxy são dados que parecem neutros mas funcionam como substitutos para raça ou classe. No contexto brasileiro, algumas variáveis proxy comuns são:" },
      { type: "list", items: [
        "CEP e bairro de residência (reflexo de segregação racial histórica)",
        "Tipo de escola frequentada (pública vs. privada)",
        "Profissão ou cargo (setores com menor diversidade racial)",
        "Banco principal (bancos com menos agências em periferias)",
      ]},
      { type: "h2", text: "O que diz a lei" },
      { type: "p", text: "A LGPD (Lei 13.709/2018) classifica dados sobre raça e etnia como dados sensíveis, com proteção reforçada. O Código de Defesa do Consumidor proíbe discriminação no fornecimento de produtos e serviços. E o PL 2338/2023 (Marco Legal da IA) classifica sistemas de scoring de crédito como de alto risco." },
      { type: "h2", text: "Como corrigir o viés?" },
      { type: "p", text: "Não existe solução perfeita, mas há práticas que reduzem o viés:" },
      { type: "list", items: [
        "Auditorias regulares de equidade — comparar aprovação/negação por grupo racial",
        "Remover ou compensar variáveis proxy com alto impacto racial",
        "Diversificar a equipe que desenvolve e avalia os modelos",
        "Publicar relatórios de impacto de IA com recorte racial",
        "Criar canais de contestação acessíveis para o consumidor",
      ]},
      { type: "quote", text: "Não basta a IA ser cega à raça — ela precisa ser justa para todos os grupos raciais. Cegueira de cor em dados históricamente enviesados perpetua a discriminação, não a elimina.", author: "Pesquisadores do Laboratório de Viés em IA — USP" },
      { type: "h2", text: "O que você pode fazer" },
      { type: "p", text: "Se você acredita ter sido discriminado por um sistema de crédito, pode acionar o PROCON, o Banco Central (para produtos financeiros) ou o SENACON. O Marco Legal da IA, quando aprovado, criará obrigações específicas de auditoria para esses sistemas." },
    ],
  },

  {
    slug: "pl-2338-2023-empresas-brasileiras",
    titulo: "PL 2338/2023: o que muda para empresas brasileiras",
    desc: "Guia prático sobre o Projeto de Lei de IA do Brasil — obrigações, prazos e impactos para cada setor.",
    tempo: "14 min",
    tags: [{ label: "Legislação", cls: "tagLegis" }],
    autor: "IA Fala Brasil",
    data: "Fev 2026",
    conteudo: [
      { type: "p", text: "O PL 2338/2023 — Projeto de Lei que institui o Marco Legal da Inteligência Artificial no Brasil — está em tramitação no Senado Federal e, quando aprovado, será a legislação mais abrangente sobre IA na América Latina. Este guia explica o que muda para empresas que já usam ou planejam usar IA." },
      { type: "h2", text: "Qual é a lógica central do PL?" },
      { type: "p", text: "O projeto segue uma lógica de regulação baseada em risco: quanto maior o potencial de dano de um sistema de IA, maiores as obrigações de quem o desenvolve e usa. Isso é inspirado no EU AI Act europeu, mas adaptado à realidade brasileira." },
      { type: "h2", text: "Classificação de risco" },
      { type: "table", headers: ["Nível de Risco", "Exemplos", "Obrigações"], rows: [
        ["Risco excessivo (proibido)", "Score social estilo China, manipulação subliminar, reconhecimento emocional em espaços públicos", "Proibidos no Brasil"],
        ["Risco alto", "Crédito, saúde, educação, recrutamento, segurança pública", "Auditoria, explicabilidade, log de decisões, avaliação de impacto"],
        ["Risco limitado", "Chatbots, geração de texto, imagem", "Transparência: informar que é IA"],
        ["Risco mínimo", "Filtros de spam, recomendação de playlist", "Sem obrigações específicas"],
      ]},
      { type: "h2", text: "Principais obrigações para empresas" },
      { type: "h3", text: "1. Transparência" },
      { type: "p", text: "Toda interação com um sistema de IA que afete decisões sobre pessoas deve ser identificada como tal. Um chatbot de atendimento deve informar que é uma IA. Uma decisão de crédito tomada por algoritmo deve ser comunicada ao consumidor." },
      { type: "h3", text: "2. Explicabilidade" },
      { type: "p", text: "Sistemas de alto risco devem ser capazes de explicar suas decisões de forma compreensível. Não basta dizer 'o algoritmo negou' — é preciso poder informar os fatores que levaram à decisão." },
      { type: "h3", text: "3. Avaliação de Impacto Algorítmico (AIA)" },
      { type: "p", text: "Empresas que operam sistemas de alto risco devem realizar e publicar uma Avaliação de Impacto Algorítmico — similar ao RIPD da LGPD, mas focado em efeitos discriminatórios e riscos sistêmicos." },
      { type: "h3", text: "4. Supervisão humana" },
      { type: "p", text: "Decisões de alto risco que afetam indivíduos devem ter revisão humana disponível. O consumidor deve poder solicitar revisão por um humano qualificado." },
      { type: "callout", icon: "📅", title: "Prazo esperado", text: "A aprovação é esperada para 2026, com período de adaptação de 12 a 24 meses para empresas. Mas empresas que já adotam as boas práticas estarão em vantagem competitiva e reduzindo riscos legais desde já." },
      { type: "h2", text: "Setores mais impactados no Brasil" },
      { type: "list", items: [
        "Fintechs e bancos: scoring de crédito e detecção de fraude são alto risco",
        "Healthtechs: diagnóstico assistido por IA é alto risco",
        "RH e recrutamento: triagem de currículos por IA é alto risco",
        "Seguradoras: precificação com IA pode ser alto risco",
        "EdTechs: sistemas de avaliação automática são alto risco",
        "Varejo: precificação dinâmica é risco limitado/mínimo",
      ]},
      { type: "h2", text: "Diferença entre o PL brasileiro e o EU AI Act" },
      { type: "p", text: "O PL brasileiro é menos prescritivo que o europeu — dá mais espaço para regulação setorial e autorregulação. Também prevê tratamento diferenciado para startups e MPEs, buscando não sufocar a inovação nacional." },
      { type: "h2", text: "Como se preparar agora" },
      { type: "list", items: [
        "Mapeie todos os sistemas de IA em uso na sua empresa",
        "Classifique-os por nível de risco segundo o PL",
        "Para sistemas de alto risco: documente decisões e crie trilha de auditoria",
        "Revise cláusulas contratuais com fornecedores de IA",
        "Designe um responsável por IA (AI Officer) na empresa",
        "Acompanhe a tramitação no Senado (senado.leg.br)",
      ]},
    ],
  },

  {
    slug: "ia-sala-de-aula-autoria",
    titulo: "Como usar IA em sala de aula sem perder a autoria",
    desc: "Estratégias pedagógicas para professores integrarem IA de forma crítica e produtiva na BNCC.",
    tempo: "9 min",
    tags: [{ label: "Educação", cls: "tagEduc" }],
    autor: "IA Fala Brasil",
    data: "Mar 2026",
    conteudo: [
      { type: "p", text: "A chegada da IA generativa nas escolas brasileiras criou um dilema real: proibir e fingir que não existe, ou integrar e ensinar a usar de forma crítica? A segunda opção é mais trabalhosa — mas é a única que prepara os estudantes para o mundo real." },
      { type: "h2", text: "O problema da proibição" },
      { type: "p", text: "Proibir o uso de IA na escola não impede que os alunos a usem em casa. Cria apenas um hiato entre a vida escolar e a vida real — e perde a oportunidade de desenvolver competências críticas essenciais para o século XXI." },
      { type: "callout", icon: "📊", title: "Dado importante", text: "Uma pesquisa do CETIC.br (2024) mostrou que 67% dos estudantes brasileiros do ensino médio já usaram IA generativa para tarefas escolares. Desse total, 80% não receberam nenhuma orientação sobre como usar corretamente." },
      { type: "h2", text: "Alinhamento com a BNCC" },
      { type: "p", text: "A BNCC inclui, nas competências gerais, o 'pensamento computacional', a 'cultura digital' e a 'argumentação'. O uso crítico de IA desenvolve exatamente essas competências — desde que a proposta pedagógica seja bem estruturada." },
      { type: "h2", text: "Estratégias que funcionam" },
      { type: "h3", text: "1. IA como rascunho, aluno como autor" },
      { type: "p", text: "Peça ao aluno que use a IA para gerar um primeiro rascunho sobre um tema. Em seguida, ele deve revisar, corrigir erros, adicionar exemplos da sua realidade e reescrever com suas próprias palavras. A avaliação recai sobre o processo de revisão, não o rascunho inicial." },
      { type: "h3", text: "2. Detectar e corrigir erros da IA" },
      { type: "p", text: "Gere um texto com erros intencionais usando IA e peça que os alunos os encontrem. Ou peça que a IA escreva sobre um tema que eles já estudaram — e que avaliem a precisão. Isso desenvolve pensamento crítico e revisão de fontes." },
      { type: "h3", text: "3. Comparar fontes: IA vs. livro vs. pesquisa" },
      { type: "p", text: "Para uma mesma pergunta, compare a resposta da IA com o livro didático e com uma fonte primária (site do IBGE, Embrapa, etc.). Analise diferenças, erros e omissões em sala. Excelente para aulas de ciências, história e geografia." },
      { type: "h3", text: "4. IA como tutor de dúvidas" },
      { type: "p", text: "Oriente os alunos a usar IA para tirar dúvidas de matemática ou ciências — mas exigindo que expliquem com suas palavras a explicação recebida. 'A IA explicou que... Eu entendi como...' Isso verifica compreensão real." },
      { type: "h2", text: "O que não funciona" },
      { type: "list", items: [
        "Pedir redações sem diretrizes claras de uso de IA",
        "Avaliar apenas o produto final sem considerar o processo",
        "Proibir sem apresentar alternativas ou discutir o tema",
        "Usar IA para substituir a explicação do professor",
      ]},
      { type: "h2", text: "Documentando a autoria" },
      { type: "p", text: "Crie uma 'declaração de uso de IA' simples: o aluno descreve brevemente como usou IA na tarefa, quais partes são suas e quais foram assistidas. Isso promove transparência e reflexão, sem punir o uso responsável." },
      { type: "quote", text: "Não é sobre usar ou não usar IA. É sobre quem está no controle — o aluno ou a máquina. Nossa função é garantir que o aluno desenvolva pensamento próprio, usando todas as ferramentas disponíveis de forma consciente.", author: "Formação de professores — MEC, 2025" },
      { type: "h2", text: "Recursos gratuitos para professores" },
      { type: "list", items: [
        "Planos de aula com IA disponíveis em /professor",
        "Prompt Lab para experimentar com os alunos em /aprender/prompt-lab",
        "Detecta Fake para trabalhar checagem de informação em /aprender/detecta-fake",
        "Viés na Máquina para discutir discriminação em /aprender/vies-na-maquina",
      ]},
    ],
  },

  {
    slug: "mapa-ia-brasil",
    titulo: "Mapa da IA no Brasil: empresas, centros e iniciativas",
    desc: "Panorama completo do ecossistema de Inteligência Artificial brasileiro em 2025.",
    tempo: "12 min",
    tags: [{ label: "Pesquisa BR", cls: "tagPesquisa" }],
    autor: "IA Fala Brasil",
    data: "Fev 2026",
    conteudo: [
      { type: "p", text: "O Brasil é o maior ecossistema de tecnologia da América Latina e está rapidamente construindo sua presença no mapa global de IA. De centros de pesquisa de ponta a startups que resolvem problemas tipicamente brasileiros, o país tem mais a oferecer do que muitos imaginam." },
      { type: "h2", text: "Pesquisa acadêmica" },
      { type: "p", text: "O Brasil tem alguns dos centros de pesquisa em IA mais reconhecidos do hemisfério sul:" },
      { type: "list", items: [
        "UNICAMP — Laboratório de Inteligência Artificial e Aprendizado de Máquina (LCA), referência em NLP para o português",
        "USP — Instituto de Ciências Matemáticas e de Computação (ICMC), com grupos de IA aplicada à saúde e visão computacional",
        "UFMG — Departamento de Ciência da Computação, forte em recomendação e redes sociais",
        "PUC-Rio — Laboratório de Inteligência Artificial, pesquisa em raciocínio e IA explicável",
        "LNCC (RJ) — Laboratório Nacional de Computação Científica, pesquisa em IA para ciência",
      ]},
      { type: "h2", text: "Iniciativas do governo federal" },
      { type: "p", text: "A Estratégia Brasileira de Inteligência Artificial (EBIA), atualizada em 2024 para o período 2024–2028, define seis eixos de atuação: regulação, qualificação, pesquisa, aplicações no governo, infraestrutura e cooperação internacional." },
      { type: "p", text: "O BNDES tem um programa de financiamento para startups de IA com impacto social. A FINEP apoia pesquisa aplicada. O Ministério da Ciência, Tecnologia e Inovação (MCTI) coordena ações de IA para a indústria." },
      { type: "h2", text: "Startups brasileiras de destaque" },
      { type: "table", headers: ["Empresa", "Setor", "O que faz"], rows: [
        ["Nelogica", "Financeiro", "IA para trading e análise de mercado"],
        ["Cortex Intelligence", "B2B", "IA para inteligência de mercado e vendas"],
        ["Horus", "Acessibilidade", "IA de visão para pessoas com deficiência visual"],
        ["Dasa / Grupo Fleury", "Saúde", "IA para diagnóstico por imagem"],
        ["Sami", "Saúde", "Plano de saúde com triagem por IA"],
        ["Gupy", "RH", "Recrutamento e seleção com IA"],
        ["Nuvemshop / VTEX", "E-commerce", "IA para personalização e atendimento"],
      ]},
      { type: "h2", text: "IA made in Brazil: desafios únicos" },
      { type: "p", text: "Startups brasileiras de IA enfrentam desafios que geram oportunidades únicas:" },
      { type: "list", items: [
        "Português com variações regionais: oportunidade de NLP especializado",
        "Desigualdade socioeconômica: IA para inclusão financeira, saúde e educação",
        "Agronegócio: IA para gestão rural, análise de solo e previsão de clima",
        "Cidades inteligentes: gestão de trânsito, segurança e infraestrutura",
        "Judiciário: milhões de processos criam demanda por IA jurídica",
      ]},
      { type: "h2", text: "O problema do talento" },
      { type: "p", text: "O maior gargalo do ecossistema brasileiro de IA é a escassez de profissionais qualificados. Estimativas do setor apontam para um déficit de 500 mil profissionais de dados e IA até 2030. Programas como o ITA, INATEL e os cursos técnicos do SENAI estão respondendo, mas a velocidade precisa aumentar." },
      { type: "callout", icon: "🚀", title: "Oportunidade para você", text: "O Brasil precisa urgentemente de profissionais que combinem conhecimento técnico em IA com entendimento do contexto local. Se você está começando agora, esse é o momento certo — a demanda por profissionais supera muito a oferta." },
    ],
  },

  {
    slug: "deepfakes-detectar-proteger",
    titulo: "Deepfakes: como detectar e se proteger",
    desc: "Técnicas de verificação e ferramentas gratuitas para identificar vídeos e áudios gerados por IA.",
    tempo: "7 min",
    tags: [{ label: "Técnico", cls: "tagTecnico" }, { label: "Ética & IA", cls: "tagEtica" }],
    autor: "IA Fala Brasil",
    data: "Mar 2026",
    conteudo: [
      { type: "p", text: "Deepfake é um conteúdo — vídeo, áudio ou imagem — gerado ou manipulado por inteligência artificial para parecer real. A tecnologia está cada vez mais acessível, e no Brasil, deepfakes já foram usados em golpes financeiros, revenge porn e desinformação política." },
      { type: "callout", icon: "⚠️", title: "Dado alarmante", text: "Em 2024, o Brasil registrou um aumento de 340% em fraudes usando clonagem de voz por IA, segundo a Febraban. A maioria dos golpes envolve voz clonada de familiar pedindo dinheiro com urgência por WhatsApp." },
      { type: "h2", text: "Tipos de deepfake" },
      { type: "list", items: [
        "Troca de rosto em vídeo (face swap): rosto de pessoa A no corpo de pessoa B",
        "Clonagem de voz: geração de áudio com a voz de qualquer pessoa a partir de poucos segundos de gravação",
        "Lip sync: sincronização de lábios para fazer alguém 'dizer' qualquer coisa",
        "Imagens sintéticas: pessoas que nunca existiram, geradas por IA",
        "Vídeos políticos: deepfakes de políticos e figuras públicas dizendo coisas falsas",
      ]},
      { type: "h2", text: "Como identificar deepfakes de vídeo" },
      { type: "p", text: "Deepfakes ainda têm 'costuras' que os treinados conseguem perceber:" },
      { type: "list", items: [
        "Piscadas irregulares ou olhos com aspecto vidroso",
        "Bordas do rosto borradas ou com artefatos",
        "Iluminação inconsistente entre rosto e ambiente",
        "Movimentos de lábios não sincronizados com o áudio",
        "Orelhas, cabelo ou pescoço com distorções",
        "Micromovimentos faciais ausentes ou robóticos",
      ]},
      { type: "h2", text: "Como identificar deepfakes de áudio" },
      { type: "list", items: [
        "Pausas artificiais entre palavras",
        "Tom de voz levemente 'robótico' ou sem emoção natural",
        "Sotaque inconsistente ao longo da mensagem",
        "Ausência de ruídos de ambiente típicos (respiração, sons de fundo)",
        "Frases que não coincidem com o estilo de falar habitual da pessoa",
      ]},
      { type: "h2", text: "Ferramentas gratuitas para detectar" },
      { type: "table", headers: ["Ferramenta", "Para quê", "Acesso"], rows: [
        ["Hive Moderation", "Detecta deepfake em imagens e vídeos", "hivemoderation.com"],
        ["FotoForensics", "Analisa metadados e inconsistências em imagens", "fotoforensics.com"],
        ["TrueMedia.org", "Análise de vídeos políticos suspeitos", "truemedia.org"],
        ["InVID/WeVerify", "Verifica vídeos virais (extensão de navegador)", "invid-project.eu"],
      ]},
      { type: "h2", text: "Protocolo de verificação rápida" },
      { type: "p", text: "Ao receber um vídeo ou áudio suspeito:" },
      { type: "list", items: [
        "Não compartilhe antes de verificar — o compartilhamento é parte do golpe",
        "Faça uma busca reversa da imagem no Google ou TinEye",
        "Ligue diretamente para a pessoa para confirmar a autoria",
        "Verifique em sites de checagem: Agência Lupa, Aos Fatos, UOL Confere",
        "Use as ferramentas de detecção listadas acima",
      ]},
      { type: "h2", text: "Proteção pessoal" },
      { type: "list", items: [
        "Limite quem pode ver suas fotos e vídeos nas redes sociais",
        "Crie uma palavra-código com familiares para confirmar identidade em emergências",
        "Desconfie de pedidos urgentes de dinheiro por mensagem, mesmo com voz conhecida",
        "Denuncie deepfakes ao SaferNet Brasil (safernet.org.br)",
      ]},
      { type: "h2", text: "O que diz a lei no Brasil" },
      { type: "p", text: "O Brasil ainda não tem lei específica sobre deepfakes, mas algumas condutas já são criminalizadas: pornografia de vingança (Lei 13.718/2018), estelionato (Código Penal), injúria e difamação. O Marco Legal da IA deve incluir regulação específica para deepfakes em eleições e golpes financeiros." },
    ],
  },
];

export function getArtigo(slug: string): Artigo | undefined {
  return artigos.find((a) => a.slug === slug);
}
